django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


urlpatterns = [
    path("", views.home),
    path("admin/", admin.site.urls),
    path("stock/", include("stock.urls", namespace="stock")),
]

stock/urls.py
from django.urls import path
from . import views

app_name = "stock"

urlpatterns = [
    path("", views.home, name="home"),
    path("all-items", views.all_items, name="all-items"),
    path("all-categories", views.browse_by_category, name="all-categories"),
    path("category/<category>", views.list_by_category, name="list-by-category"),
    path("search/<keyword>", views.search_by_slug, name="search"),
    path("all-warehouses", views.browse_by_warehouse, name="all-warehouses"),
    path("warehouse/<warehouse>", views.list_by_warehouse, name="list-by-warehouse"),
    path("warehouse/<warehouse>/<filter>", views.list_by_warehouse_filter, name="list-by-warehouse-filter"),
    path("category/<category>/<filter>", views.list_by_category_filter, name="list-by-category-filter")
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render (request, "home/home.html")
    #return HttpResponse("<h2>Welcome to the store!</h2><a href='/stock/all-items'>Check out our stock</a>")

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static 'home/style.css' %}">
<head>
    <title>{% block head-content %}{% endblock head-content %}</title>
</head>
<body>
    {% block content_title %}{% endblock content_title %}
    {% block content %}{% endblock content %}
</body>
</html> 

home/templates/home/home.html
{% extends "home/base.html" %}

{% block content_title %}<h2>Welcome to our shop!</h2>{% endblock content_title %}
{% block content %}<a href={% url 'stock:home' %}>Visit our stock</a>{% endblock content %}