django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


urlpatterns = [
    path("", views.home),
    path("admin/", admin.site.urls),
    path("stock/", include("stock.urls", namespace="stock")),
]

stock/urls.py
from django.urls import path
from . import views

app_name = "stock"

urlpatterns = [
    path("", views.home, name="home"),
    path("all-items", views.all_items, name="all-items"),
    path("all-categories", views.browse_by_category, name="all-categories"),
    path("category/<category>", views.list_by_category, name="list-by-category"),
    path("search/<keyword>", views.search_by_slug, name="search"),
    path("all-warehouses", views.browse_by_warehouse, name="all-warehouses"),
    path("warehouse/<warehouse>", views.list_by_warehouse, name="list-by-warehouse"),
    path("warehouse/<warehouse>/<filter>", views.list_by_warehouse_filter, name="list-by-warehouse-filter"),
    path("category/<category>/<filter>", views.list_by_category_filter, name="list-by-category-filter")
]

home/models.py
from django.db import models

# Create your models here.

stock/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Employee(models.Model):
    user_name = models.CharField(primary_key=True, max_length=10)
    password = models.CharField(max_length=20, blank=True, null=True)
    lead_by = models.ForeignKey('self', models.DO_NOTHING, db_column='lead_by', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'employee'


class Item(models.Model):
    state = models.CharField(max_length=15, blank=True, null=True)
    category = models.CharField(max_length=25, blank=True, null=True)
    warehouse = models.ForeignKey('Warehouse', models.DO_NOTHING, blank=True, null=True)
    date_of_stock = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.category, self.state, self.date_of_stock
    
    class Meta:
        managed = False
        db_table = 'item'
        ordering = ["date_of_stock"]



class Warehouse(models.Model):

    class Meta:
        managed = False
        db_table = 'warehouse'


class Author(models.Model):
    author = models.CharField(max_length=50)

    def __str__(self):
        return self.author

class Comment(models.Model):
    comment = models.TextField(null=True, blank=True) 

    def __str__(self):
        return self.comment
    

class Post(models.Model):
    content = models.TextField(null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.content

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render (request, "home/home.html")
    #return HttpResponse("<h2>Welcome to the store!</h2><a href='/stock/all-items'>Check out our stock</a>")

stock/views.py
from django.shortcuts import render, HttpResponse
from .models import Item

# Create your views here.

def home(request):
    return render(request, "stock/home.html")

def all_items(request):
    all_items_data = Item.objects.all()
    return render(request, "stock/all-items.html", {"all_items_data": all_items_data})

def browse_by_category(request):
    categories = []
    all_items_data = Item.objects.all()
    for item in all_items_data:
        if item.category not in categories:
            categories.append(item.category)
    return render(request, "stock/all-categories.html", {"categories": categories})

def list_by_category(request, category):
    all_items_data = Item.objects.all()
    all_states = []
    for item in all_items_data:
        if item.state not in all_states: all_states.append(item.state)
    return render(request, "stock/list-by-category.html", {"all_items_data": all_items_data, "category": category, "all_states": all_states})

def list_by_category_filter(request, category, filter):
    all_items_data = Item.objects.all()
    filtered_data = []
    for item in all_items_data:
        if str(item.category) == str(category) and str(item.state) == str(filter):
            filtered_data.append(item)
    return render(request, "stock/list-by-category-filter.html", {"filtered_data": filtered_data, "category": category, "filter": filter})


def search_by_slug(request, keyword):
    all_items_data = Item.objects.all()
    return render(request, "stock/search-result.html", {"all_items_data": all_items_data, "keyword": keyword})

def browse_by_warehouse(request):
    warehouses = []
    all_items_data = Item.objects.all()
    for item in all_items_data:
        if item.warehouse not in warehouses:
            warehouses.append(item.warehouse)
    return render(request, "stock/all-warehouses.html", {"warehouses": warehouses})

def list_by_warehouse(request, warehouse):
    all_items_data = Item.objects.all()
    filtered_data = []
    all_states = []
    for item in all_items_data:
        if item.state not in all_states: all_states.append(item.state)
        if str(item.warehouse) == str(warehouse):
            filtered_data.append(item)
    print(all_states)
    return render(request, "stock/list-by-warehouse.html", {"filtered_data": filtered_data, "all_states": all_states, "warehouse": warehouse})

def list_by_warehouse_filter(request, warehouse, filter):
    all_items_data = Item.objects.all()
    filtered_data = []
    for item in all_items_data:
        if str(item.warehouse) == str(warehouse) and str(item.state) == str(filter):
            filtered_data.append(item)
    return render(request, "stock/list-by-warehouse-filter.html", {"filtered_data": filtered_data, "warehouse": warehouse, "filter": filter})

stock/templates/stock/all-categories.html
{% extends "stock/base.html" %}

{% block head-content %}All categories{% endblock head-content %}

{% block content_title %}<h2>All categories</h2>{% endblock content_title %}

{% block content %}

<table>
  <tr>
    <th>Category</th>
  </tr>
  {% for item in categories %}
  <tr>
    <td><a href={% url 'stock:list-by-category' item %}>{{ item }}</a></td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

stock/templates/stock/all-items.html
{% extends "stock/base.html" %}

{% block head-content %}All items{% endblock head-content %}

{% block content_title %}<h2>All items in all warehouses</h2>{% endblock content_title %}

{% block content %}


<table>
  <tr>
    <th>ID</th>
    <th>Item</th>
    <th>State</th>
    <th>Date of stock</th>
    <th>Location</th>
  </tr>

  {% for item in all_items_data %}
  <tr>
    <td>{{ item.id }}</td>
    <td><a href={% url 'stock:search' item.category %}>{{ item.category }}</a></td>
    <td>{{ item.state }}</td>
    <td>{{ item.date_of_stock }}</td>
    <td>{{ item.warehouse }}</td>
  </tr>
  {% endfor %}

</table>

{% endblock content %}

stock/templates/stock/all-warehouses.html
{% extends "stock/base.html" %}

{% block head-content %}All warehouses{% endblock head-content %}

{% block content_title %}<h2>All warehouses</h2>{% endblock content_title %}

{% block content %}


<table>
  <tr>
    <th>Warehouse</th>
  </tr>
  {% for item in warehouses %}
  <tr>
    <td><a href={% url 'stock:list-by-warehouse' item %}>{{ item }}</a></td>
  </tr>
  {% endfor %}
</table>

     
{% endblock content %}

stock/templates/stock/base.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static 'stock/style.css' %}">
<head>
    <title>{% block head-content %}{% endblock head-content %}</title>
</head>
    {% block nav %}{% include 'stock/navbar.html' %}{% endblock nav %}
    {% block content_title %}{% endblock content_title %}
    {% block content %}{% endblock content %}
</body>
</html>

stock/templates/stock/home.html
{% extends "stock/base.html" %}

{% block head-content %}Our stock{% endblock head-content %}

{% block content_title %}<h2>Browse our stock</h2>{% endblock content_title %}

{% block content %}{% endblock content %}

stock/templates/stock/list-by-category-filter.html
{% extends "stock/base.html" %}

{% block head-content %}List by category{% endblock head-content %}

{% block content_title %}<h2>Filtered by: "{{ filter }}" in {{ category }}</h2>{% endblock content_title %}

{% block content %}
    <table>
        <tr>
          <th>ID</th>
          <th>Item</th>
          <th>State</th>
          <th>Date of stock</th>
          <th>Location</th>
        </tr>
        
        {% for item in filtered_data %}
        <tr>
          <td>{{ item.id }}</td>
          <td><a href={% url 'stock:search' item.category %}>{{ item.category }}</a></td>
          <td>{{ item.state }}</td>
          <td>{{ item.date_of_stock }}</td>
          <td>{{ item.warehouse }}</td>
        </tr>
        {% endfor %}
      
      </table> 
      

  <br><h2><a href={% url 'stock:all-categories' %}>Back to all categories</a></h2>
{% endblock content %}

stock/templates/stock/list-by-category.html
{% extends "stock/base.html" %}

{% block head-content %}List by category{% endblock head-content %}

{% block content_title %}<h2>List by category</h2>{% endblock content_title %}

{% block content %}

<h3>
  Filter for: 
  {% for state in all_states %}
    <a href={% url 'stock:list-by-category-filter' category state %}>{{ state }}</a>
  {% endfor %}
</h3>

    <table>
        <tr>
          <th>ID</th>
          <th>Item</th>
          <th>State</th>
          <th>Date of stock</th>
          <th>Location</th>
        </tr>
        
        {% for item in all_items_data %}
        {% if item.category == category %}
        <tr>
          <td>{{ item.id }}</td>
          <td><a href={% url 'stock:search' item.category %}>{{ item.category }}</a></td>
          <td>{{ item.state }}</td>
          <td>{{ item.date_of_stock }}</td>
          <td>{{ item.warehouse }}</td>
        </tr>
        {% endif %}
        {% endfor %}
      
      </table> 
      

  <br><h2><a href={% url 'stock:all-categories' %}>Back to all categories</a></h2>
{% endblock content %}

stock/templates/stock/list-by-warehouse-filter.html
{% extends "stock/base.html" %}

{% block head-content %}List by category{% endblock head-content %}

{% block content_title %}<h2>Filtered by: "{{ filter }}" in {{ warehouse }}</h2>{% endblock content_title %}

{% block content %}
    <table>
        <tr>
          <th>ID</th>
          <th>Item</th>
          <th>State</th>
          <th>Date of stock</th>
          <th>Location</th>
        </tr>
        
        {% for item in filtered_data %}
        <tr>
          <td>{{ item.id }}</td>
          <td><a href={% url 'stock:search' item.category %}>{{ item.category }}</a></td>
          <td>{{ item.state }}</td>
          <td>{{ item.date_of_stock }}</td>
          <td>{{ item.warehouse }}</td>
        </tr>
        {% endfor %}
      
      </table> 
      

  <br><h2><a href={% url 'stock:all-categories' %}>Back to all categories</a></h2>
{% endblock content %}

stock/templates/stock/list-by-warehouse.html
{% extends "stock/base.html" %}

{% block head-content %}List by warehouse{% endblock head-content %}

{% block content_title %}<h2>All items in {{ warehouse }}</h2>{% endblock content_title %}

{% block content %}

<h3>
  Filter for: 
  {% for state in all_states %}
    <a href={% url 'stock:list-by-warehouse-filter' warehouse state %}>{{ state }}</a>
  {% endfor %}
</h3>

<table>
  <tr>
    <th>ID</th>
    <th>Item</th>
    <th>State</th>
    <th>Date of stock</th>
    <th>Location</th>
  </tr>
  
  {% for item in filtered_data %}
  <tr>
    <td>{{ item.id }}</td>
    <td><a href={% url 'stock:search' item.category %}>{{ item.category }}</a></td>
    <td>{{ item.state }}</td>
    <td>{{ item.date_of_stock }}</td>
    <td>{{ item.warehouse }}</td>
  </tr>
  {% endfor %}

</table> 



  <br><h2><a href={% url 'stock:all-warehouses' %}>Back to all warehouses</a></h2>
{% endblock content %}

stock/templates/stock/navbar.html
<h3>Navigation: <a href={% url 'stock:all-items' %}>List all items</a> | <a href={% url 'stock:all-categories' %}>Browse by categories</a>| <a href={% url 'stock:all-warehouses' %}>Browse by warehouses</a> | <a href="">Search</a></h3>

stock/templates/stock/search-result.html
{% extends "stock/base.html" %}

{% block head-content %}Search result{% endblock head-content %}

{% block content_title %}<h2>List fitting results for: {{ keyword }} (all warehouses)</h2>{% endblock content_title %}

{% block content %}
    <table>
        <tr>
          <th>ID</th>
          <th>Item</th>
          <th>State</th>
          <th>Date of stock</th>
          <th>Location</th>
        </tr>
        
        {% for item in all_items_data %}
        {% if keyword in item.category %}
        <tr>
          <td>{{ item.id }}</td>
          <td><a href={% url 'stock:search' item.category %}>{{ item.category }}</a></td>
          <td>{{ item.state }}</td>
          <td>{{ item.date_of_stock }}</td>
          <td>{{ item.warehouse }}</td>
        </tr>
        {% endif %}
        {% endfor %}
      
      </table>
      

  <br><h2><a href={% url 'stock:all-categories' %}>Back to all categories</a></h2>
{% endblock content %}